# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- 3.1
- 3.2
- oldrel
- release
- devel

matrix:
  allow_failures:
    - r: 3.1

warnings_are_errors: false

env:
  - _R_CHECK_FORCE_SUGGESTS_=true
  
compiler:
  - gcc-4.9

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - gfortran-4.9
before_install:
  - echo "options(repos = c(CRAN = 'https://cran.rstudio.com'))" > ~/.Rprofile
  - mkdir ~/.R
  - echo "CXX11=g++-4.9" > ~/.R/Makevars
  - echo "CXX=g++-4.9" >> ~/.R/Makevars
  - echo "CXX1X=g++-4.9" >> ~/.R/Makevars

after_success:
  - Rscript -e 'covr::codecov()'