# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

env:
  global:
  - MAKEFLAGS="-j 2"
  
r_github_packages:
  - r-lib/pkgdown
  - tidyverse/tidytemplate
  
matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'

  - r: oldrel
  - r: 3.2
  - r: 3.1
  allow_failures:
  - r: 3.2
  - r: 3.1
  
warnings_are_errors: false
